---
# tasks file for create_venv

- name: install cdn packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ cdn_packages }}"

- name: create temp directory to hold python packages
  file:
    path: "{{ temp_dir }}"
    state: directory
    mode: '0755'

- name: copy python binaries to temp directory
# held in role for testing, eventually host these files on sat
  copy:
    src: "{{ item }}"
    dest: "{{ temp_dir }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ py_packages }}"

- name: create venv
# not idempotent, look into resolving
  shell: "python3 -m  venv {{ venv }}"

- name: install python packages using rqmts file
  pip:
    virtualenv: "{{ venv }}"
    requirements: "{{ role_path }}/files/requirements.txt"
    extra_args: "--no-index --find-links=file://{{ temp_dir }}"
